apiVersion: isovalent.com/v1
kind: IsovalentEgressGatewayPolicy
metadata:
  name: # set by the check package in WithIsovalentEgressGatewayPolicy()
spec:
  selectors:
  - podSelector:
      matchLabels:
        io.kubernetes.pod.namespace: cilium-test-1
        kind: # set by the check package in WithIsovalentEgressGatewayPolicy()
  destinationCIDRs:
  - 0.0.0.0/0
  excludedCIDRs: # set by the check package in WithIsovalentEgressGatewayPolicy()
  egressGroups: # set by the check package in WithIsovalentEgressGatewayPolicy()
