on:
  pull_request:
    branches:
      - 'main-ce'
  push:
    tags:
      - 'enterprise/cilium-cli/v[0-9]+.[0-9]+.[0-9]+-cee.[0-9]+'

name: Create cilium-cli CEE release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get image tag
        id: tag
        run: |
          tag=${GITHUB_REF##*/}
          oss_tag=$(echo $tag | cut -d "-" -f 1)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "oss_tag=$oss_tag" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'enterprise/cilium-cli/go.mod'

      - name: Generate artifacts
        run: |
          git config --global url."https://${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}:@github.com/".insteadOf "https://github.com/"
          git config --global --add url."https://${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}:@github.com/".insteadOf "git@github.com:"
          cd enterprise/cilium-cli
          make enterprise-release

      - name: Create a Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2
        with:
          repository: isovalent/cilium-cli-releases
          name: ${{ steps.tag.outputs.tag }}
          tag_name: ${{ steps.tag.outputs.tag }}
          # Need to use PAT with "repo" access to create a release in another repo.
          token: ${{ secrets.ISOVALENT_BOT_READ_PRIVATE_REPOSITORIES }}
          draft: true
          files: |
            enterprise/cilium-cli/release/*
          body: |
            # cilium-cli ${{ steps.tag.outputs.tag }} release

            This release is based on ${{ steps.tag.outputs.oss_tag }} cilium-cli
            and adds sysdump collectors and connectivity tests that are specific
            to Isovalent Enterprise for Cilium.

            Future releases might see additional enterprise-specific features.
